version: '3'
services:
  slate:
    build: .
    image: local/external-api-docs_slate
    command: ["build"]
    volumes:
      - "./build:/srv/slate/build"
      - "./source:/srv/slate/source"
  slate_serve:
    image: local/external-api-docs_slate
    command: ["serve"]
    ports:
      - "4567:4567"
    volumes:
      - "./source:/srv/slate/source"
    depends_on:
      - slate
